name: Download, Unzip to g/, and Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Download h.zip from direct URL
        env:
          H_URL: "https://github.com/justpl0y/justpl0y/releases/download/sowwy/h.zip"
        run: |
          curl -L -o h.zip "$H_URL"

      - name: Unzip h.zip into g/ and touch files
        run: |
          mkdir -p g
          unzip -o h.zip -d g
          # Update modification time to ensure git detects changes
          find g -type f -exec touch {} +

      - name: Commit and push extracted files
        run: |
          git add g
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 1
          else
            git commit -m "Unzip h.zip into g/"
            git push origin HEAD
          fi
