name: Download, Unzip to g/, and Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Download h.zip from Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          RELEASE_TAG="v1.0" # replace with your release tag
          ASSET_NAME="h.zip" # replace with your asset name

          ASSET_ID=$(gh release view $RELEASE_TAG --repo $REPO --json assets | jq -r ".assets[] | select(.name==\"$ASSET_NAME\") | .id")
          curl -L -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/octet-stream" \
               -o h.zip \
               "https://api.github.com/repos/$REPO/releases/assets/$ASSET_ID"

      - name: Unzip h.zip into g/
        run: |
          mkdir -p g
          unzip -o h.zip -d g

      - name: Commit and push extracted files
        run: |
          git add g
          git diff --quiet && echo "No changes to commit" || git commit -m "Unzip h.zip into g/"
          git push origin HEAD
