name: Download, Unzip to g/, and Commit

on:
  workflow_dispatch:

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download h.zip from Release
        run: |
          curl -L -o h.zip "https://release-assets.githubusercontent.com/github-production-release-asset/1055132028/b811f265-8688-4be4-92bf-01f7457cd26d?sp=r&sv=2018-11-09&sr=b&spr=https&se=2025-09-26T01%3A58%3A40Z&rscd=attachment%3B+filename%3Dh.zip&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2025-09-26T00%3A58%3A34Z&ske=2025-09-26T01%3A58%3A40Z&sks=b&skv=2018-11-09&sig=18ABMGYSK7VdzeDoTFPq1pwqT7PwjQs8BrnXhUIC38k%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc1ODg1MDE0MCwibmJmIjoxNzU4ODQ5ODQwLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.LpNPqpdP1jT-vJrjF7fmXSsolYEQu1Cbl6YtxBFtBmQ"

      - name: Unzip h.zip into g/
        run: |
          mkdir -p g
          unzip -o h.zip -d g

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push extracted files
        run: |
          git add g
          git diff --quiet && echo "No changes to commit" || git commit -m "Unzip h.zip into g/"
          git push
